[package]
name = "ark-curve25519"
version.workspace = true
authors.workspace = true
description = "The curve25519 Montgomery curve"
homepage.workspace = true
repository.workspace = true
documentation = "https://docs.rs/ark-curve25519/"
keywords.workspace = true
categories.workspace = true
include.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
ark-ff = { workspace = true }
ark-ec = { workspace = true }
ark-std = { workspace = true }
ark-r1cs-std = { workspace = true, optional = true }

[dev-dependencies]
ark-relations = { workspace = true }
ark-serialize = { workspace = true }
ark-algebra-test-templates = { workspace = true }
ark-algebra-bench-templates = { workspace = true }
ark-curve-constraint-tests = { path = "../curve-constraint-tests" }

[features]
default = []
std = [ "ark-std/std", "ark-ff/std", "ark-ec/std" ]
r1cs = [ "ark-r1cs-std" ]
asm = [ "ark-ff/asm" ]

[[bench]]
name = "curve25519"
path = "benches/curve25519.rs"
harness = false
