[package]
name = "ark-poly"
version = "0.1.0"
authors = [ "arkworks contributors" ]
description = "A library for efficient polynomial arithmetic via FFTs over finite fields"
homepage = "https://arkworks.rs"
repository = "https://github.com/arkworks/algebra"
documentation = "https://docs.rs/ark-poly/"
keywords = ["cryptography", "finite fields", "fft", "polynomials"]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
ark-ff = { path = "../ff", default-features = false }
ark-std = { git = "https://github.com/arkworks-rs/utils", default-features = false }
rand = { version = "0.7", default-features = false }
rayon = { version = "1", optional = true }
derivative = { version = "2", default-features = false, features = [ "use_core" ] }

[dev-dependencies]
ark-test-curves = { path = "../test-curves", default-features = false, features = [ "bls12_381_curve", "mnt4_753_curve"] }

[features]
default = []
std = [ "ark-std/std", "ark-ff/std" ]
parallel = [ "std", "ark-ff/parallel", "rayon", "ark-std/parallel" ]
